Shonen-Labs/StarkFinder

.github/workflows/contributors.yml, .gitignore, update_readme.py
=> contributors yaml file created

client/components/playground/Modal/Compile/ContractCode.tsx, client/components/playground/Modal/Compile/GenerateCode.tsx
resolves #18 
Changes :
- Redesign of the popup ui
=> fix: popup UI

client/components/playground/floatingWindow/FloatingSidebar.tsx, client/components/playground/floatingWindow/data.ts
This PR adds new function blocks to enhance the DevXStark route, allowing users to include more types of functionalities in their contracts.
Resolves #16
=> feat: Add new common function blocks for DevXStark

client/app/api/transactions/route.ts, client/prisma/schema.prisma
=> feat(api): add transaction chat and message storage with Prisma

client/fetch_data.py, fetch_data.py
fixes #22
Filter tokens function still left
=> fetch yield and token data

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Please review. Thanks for the Patience 🙏❤
=> workflow template completed

client/app/tg/TelegramMiniApp.tsx
=> feat: Adding interactive buttons to telegram miniapp

client/app/api/deploy-contract/route.ts, client/app/tg/TelegramMiniApp.tsx, client/package-lock.json, client/package.json, package-lock.json
=> bumped up prisma to latest and fixed deployment issue

README.md
---
Create transaction page for starkfinder
---
Fixes #59
---
=> docs: update readme page to contain starkfinder transaction page

contracts/.tool-versions, contracts/Scarb.toml, contracts/src/lib.cairo, contracts/src/mock_erc20.cairo, contracts/src/starkfinder.cairo, contracts/tests/test_starkfinder.cairo
--- Added contract tests for register and send transaction functions. Both normal tests and panicking tests. 
--- Also added a mock token contract for the tests.
--- Closes #75 
--- Run `scarb test` command in the contracts directory
--- 
---
- [Done] I have tested these changes locally
- [Done] Relevant documentation is updated
- [Done] My code follows the repository's coding guidelines
- [Done] I have added/updated tests that prove my fix/feature
- [Done] No breaking changes introduced
- [Done] Code is well-commented and readable
=> Added contract tests

Design.md
https://github.com/Shonen-Labs/StarkFinder/issues/74
---
---
[Reference any related issues this PR addresses (e.g., Fixes #123)]
---
1. [Step to test the first change]
2. [Step to test the second change]
3. [Additional testing steps if necessary]
---
---
=> DESIGN: Create figma wireframe for Profile page

client/.gitignore, client/package-lock.json, client/package.json, client/yarn.lock, tg_bot/bot.js, tg_bot/bot.ts, tg_bot/data/chat_history/873900274.json, tg_bot/data/user_preferences/873900274.json, tg_bot/investmentBot.js, tg_bot/investmentBot.ts, tg_bot/package-lock.json, tg_bot/package.json
---
---
[Reference any related issues this PR addresses (e.g., Fixes #123)]
---
1. [Step to test the first change]
2. [Step to test the second change]
3. [Additional testing steps if necessary]
---
---
=> fixed bot & website

client/lib/Connect.tsx, client/yarn.lock
--- Connect wallet button UI fixes
Fixed the connect wallet button UI to match its styling with the StarkFinder page 
--- #121 
---
1. Go to https://stark-finder-mq45.vercel.app/
Click on the Launch app
Click on Transaction
--- 
---
=> fix: Connect wallet button UI

contracts/src/erc20.cairo, contracts/src/lib.cairo, contracts/tests/test_erc20.cairo
Implement a standard ERC20 token contract in Cairo to be used within the Starknet ecosystem.
- Tests for all functionalities.
Fixes https://github.com/Shonen-Labs/StarkFinder/issues/110
---
1. [Step to test the first change]
2. [Step to test the second change]
3. [Additional testing steps if necessary]
---
---
=> feat: [Contract] ERC20 Token

client/app/devx/resources/page.tsx
Added a resources page at `/devx/resources` route which contains relevant and important strarknet resources
#122 
1. Go to https://stark-finder-mq45.vercel.app/
2. Go to `/devx/resources` route 
https://github.com/user-attachments/assets/30dbb5a3-e401-4b7b-b238-aaec146ee9b8
---
=> Feat: Resources page added

README.md
=> docs: the link to the license did not work

client/components/playground/floatingWindow/FloatingSidebar.tsx
Added a new nav link to the resources page (/devx/resources)
Closes #143
=> Feat: Add a sidebar navlink in DevX

contracts/src/DefiVault.cairo, contracts/src/interfaces.cairo, contracts/src/interfaces/IDefiVault.cairo, contracts/src/lib.cairo, contracts/tests/test_defi_contract.cairo
- Added reentrancy protection to secure deposit and withdrawal  function.
- Implemented strict input validations to prevent invalid transactions.
- multi-token support .
- add  yield farming/lending integrations for yield farming
Fixes #109 
=> add defi_vault

client/components/ui/tokens-modal.tsx, client/components/ui/transfer.tsx
- Improved the UI for the "Confirm Transaction" popup to make it cleaner and more intuitive.
- Adjusted layout, spacing, and button styles for better user experience.
Fixes #101 
Before: 
After:
=> Improved UI for Confirm Transaction popup in chat

contracts/Scarb.toml, contracts/src/crowdfunding.cairo, contracts/tests/test_crowdfunding.cairo
-  add  get_user_campaigns to get all user created campaigns,
- 
-   Sir  multiple campaigns dynamically support  feature already add by previous PR 
Fixes #118 
=> [Contract] AdvancedFactory: Crowdfunding

contracts/src/ConstantProductAmm.cairo, contracts/src/interfaces.cairo, contracts/src/interfaces/IConstantProductAmm.cairo, contracts/src/lib.cairo, contracts/src/mock_erc20.cairo, contracts/tests/lib.cairo, contracts/tests/test_constant_product_amm.cairo, contracts/tests/test_crowdfunding.cairo, contracts/tests/test_defi_contract.cairo, contracts/tests/test_nft_dutch.cairo
This pull request introduces a new `ConstantProductAmm` contract module along with its corresponding interface `IConstantProductAmm`. The module includes functions for swapping tokens, adding liquidity, and removing liquidity. Additionally, several test cases have been added to ensure the proper functionality of the AMM.
Fixes #112 
Please note that the test cases for the `ConstantProductAmm` have been marked as ignored, as they have a dependency on the issue https://github.com/OpenZeppelin/cairo-contracts/issues/953 to be resolved.
=> Feat: Implement Constant Product AMM Contract

contracts/src/lib.cairo, contracts/src/upgradable.cairo, contracts/tests/lib.cairo, contracts/tests/test_upgradable_contract.cairo
This pull request introduces several major changes and additions to the codebase, specifically focusing on the implementation of upgradable contracts in Cairo for StarkNet. The changes also include the addition of new tests for the upgradable contracts.
Fixes #108
=> Feat: Implementation of Upgradable Contracts for StarkNet

client/components/playground/Header/index.tsx, client/yarn.lock
closes #177
pr removes the first modal and automatically displays the sound modal on click of the connect wallet
- [ x] I have tested these changes locally
- [x ] Relevant documentation is updated
- [ x] My code follows the repository's coding guidelines
- [ x] I have added/updated tests that prove my fix/feature
- [ x] No breaking changes introduced
- [ x] Code is well-commented and readable
=> Fix wallet

client/components/playground/Playground.tsx, client/components/playground/floatingWindow/FloatingSidebar.tsx, client/yarn.lock
=> FRONTEND: Fix the broken UI of DevXStark

contracts/src/lib.cairo, contracts/src/random_num.cairo
=> Added random number generator contract

contracts/src/lib.cairo, contracts/src/simple_storage.cairo
=> Added simple storage contract

contracts/src/ConstantProductAmm.cairo, contracts/src/SimpleStorage.cairo, contracts/src/interfaces.cairo, contracts/src/interfaces/IRandomness.cairo, contracts/src/lib.cairo, contracts/src/random_num.cairo, contracts/tests/lib.cairo, contracts/tests/test_starkfinder.cairo, contracts/tests/test_storage.cairo
=> Fix :  the build errors in SimpleStorage and Random Number Generator

client/app/devx/page.tsx, client/app/globals.css, client/components/playground/Playground.tsx
FIX THE SIDENAV POSITIONING 
close-[#204 ]
this PR fixes the side bar positioning, it sets the side nav to the full height of the page and removes irrelevant overflows on both the page and the side nav. 
Fixes #204
=> Fixed the DevXStark page Navbar UI

client/app/agent/c/[id]/page.tsx, client/components/landing/home/modal-landing.tsx, client/package-lock.json, client/package.json
i refactored the ui component for the lanuch app  modal and also removed the new chat and new tnx from the side bar
https://github.com/Shonen-Labs/StarkFinder/issues/208
fixes #208 
- [ x ] I have tested these changes locally
- [ x ] My code follows the repository's coding guidelines
=> Refactor: remove some of the components that wasnt necessary

client/app/api/transactions/route.ts, client/components/ui/bridge.tsx, client/lib/transaction/handlers/bridge.ts, client/types/crypto-coin.ts
I have implemented the the Bridging functionality for the popup and connected it to `/api/transactions` api route 
Fixes #106
Closes #106
=> FEAT: Implement Bridging functionality from the dropdown/popup

.github/workflows/ci-cd.yml, contracts/src/DefiVault.cairo, contracts/src/crowdfunding.cairo, contracts/src/mock_erc20.cairo, contracts/src/starkfinder.cairo, contracts/src/upgradable.cairo, contracts/tests/test_constant_product_amm.cairo, contracts/tests/test_crowdfunding.cairo, contracts/tests/test_defi_contract.cairo, contracts/tests/test_erc20.cairo, contracts/tests/test_nft_dutch.cairo, contracts/tests/test_starkfinder.cairo, contracts/tests/test_starkidentity.cairo, contracts/tests/test_storage.cairo, contracts/tests/test_timelock.cairo, contracts/tests/test_upgradable_contract.cairo
Fix the Contracts CI/CD actions not working
Fixes #210 
=> Fix the Contracts CI/CD actions not working

client/app/tg/TelegramMiniApp.tsx, client/lib/wallet/argentwallet.ts, client/package-lock.json, client/package.json
Worked on integrating the new invisible sdk, thereby replacing the already existing deprecated "@argent/tma-wallet" package. Made sure I could connect wallet using invisible sdk and removed the "SessionAccountInterface" that came with  "@argent/tma-wallet" on the connect wallet page
Fixes #215
=> Feat: Integrate invisible sdk

client/components/playground/Playground.tsx, client/components/playground/floatingWindow/FloatingSidebar.tsx
I added a scroll bar to the custom code block so the code in cairo can be seen as more content is added into the block 
Fixes #226 
=> fix: add scrollbar to custom code block

client/app/api/ask/route.ts
Use OpenAI's GPT API as the primary response generator.
Fallback to BrianAI if OpenAI fails.
Take user messages as input and return AI-generated responses.
----------
To fix this  bug 
I've created the /api/ask route, which:
Uses OpenAI's GPT model first.
Falls back to BrianAI if OpenAI fails.
Returns AI-generated responses.
Fixes #218 
=> Fix-Ask-chat-is-not-working-for-starkFinder

client/app/devx/page.tsx, client/components/playground/Header/index.tsx, client/lib/Connect.tsx
I've fixed the wallet connection functionality in the modal. The key changes are:
- Added `useConnect` hook from @starknet-react/core to handle wallet connections
- Added a `handleConnect` function that properly connects to the selected wallet
- Updated the modal buttons to use the `handleConnect` function with the correct connector IDs:
- "argentX" for Argent wallet
- "braavos" for Braavos wallet
- "injected" for other injected wallets
Fixes #225 
=> Fix: Connect wallet button in DevxStark

client/components/ui/swap.tsx, client/components/ui/transfer.tsx
I changed the hardcoded values with the real time values in the wallet user, I used that same logic that what was done in the deposit file
Fixes #231
=> Fix issue 231

client/app/globals.css, client/components/playground/Blocknode/AllocateNode.tsx, client/components/playground/Blocknode/EventNode.tsx, client/components/playground/Blocknode/LiquidityNode.tsx, client/components/playground/Blocknode/StakeNode.tsx, client/components/playground/Blocknode/SwapNode.tsx, client/components/playground/Blocknode/index.tsx, client/components/playground/Playground.tsx
This PR fixes the node highlighting issues in the flow editor UI, making it immediately clear which node is currently selected by the user.
Fixes #224 - "Fix: highlight issues when nodes are clicked"
The solution implements a consistent visual highlighting system across all node components:
1. Added new CSS classes to globals.css:
- `.shadow-glow` with pulsing animation for visual emphasis
- `.ring-4` and `.ring-white` for consistent white border styling 
- `.node-selected` with subtle scale transformation (1.05x) and z-index priority
2. Updated component implementations:
- Added selection state detection to all node components (EventNode, SwapNode, etc.)
- Applied consistent border, ring, and glow effects to selected nodes
- Set higher z-index (50) for selected nodes to ensure they …
=> fix nodes highlight issues

client/app/devx/contracts/advanced-concept/hashing/page.tsx, client/app/devx/contracts/advanced-concept/plugins/page.tsx, client/app/devx/contracts/advanced-concept/sierra/page.tsx, client/app/devx/contracts/advanced-concept/verification/page.tsx, client/app/devx/contracts/applications/defi-vault/page.tsx, client/app/devx/contracts/applications/erc20-token/page.tsx, client/app/devx/contracts/applications/erc721-nft/page.tsx, client/app/devx/contracts/applications/upgradeable-contract/page.tsx, client/app/devx/contracts/cairo-cheatsheet/arrays/page.tsx, client/app/devx/contracts/cairo-cheatsheet/events/page.tsx, client/app/devx/contracts/cairo-cheatsheet/felt/page.tsx, client/app/devx/contracts/cairo-cheatsheet/maps/page.tsx, client/app/devx/contracts/components/dependencies/page.tsx, client/app/devx/contracts/components/how-to/page.tsx, client/app/devx/contracts/components/ownable/page.tsx, client/app/devx/contracts/components/storage/page.tsx, client/app/devx/contracts/getting-started/build/page.tsx, client/app/devx/contracts/getting-started/create/page.tsx, client/app/devx/contracts/getting-started/install/page.tsx, client/app/devx/contracts/getting-started/testing/page.tsx, client/app/devx/contracts/page.tsx, client/components/devx/contracts/Accordion.tsx, client/components/devx/contracts/Sidebar.tsx, client/package-lock.json, client/package.json
Create new "Example Contracts" page with UI similar to the resources page and added a sidebar similar to the one on Starknet By Example.
Fixed issue #251
=> Issue #251: Create a new Example Contracts Page

client/components/landing/home/footer.tsx
This PR updates the footer section of the StarkFinder website to improve navigation and user experience. The changes include:
- Reorganized footer menu structure with three main sections: Navigation, Company, and Social
- Added new navigation links for main app sections:
- DevX (app/devx)
- Transact (app/transactions)
- Contracts (app/contracts)
- Resources (app/resources)
- Removed irrelevant links (About, Help and Support, Privacy, Terms of Service, Partner, Image)
- Added proper TypeScript interfaces for better type safety
- Implemented external link handling for social media links with `target="_blank"` and security attributes
Fixes #241 
[Before]
https://github.com/user-attachments/assets/ba190940-aa1d-47a9-963e-77ef2a2b6825
[After] …
=> footer links have been fixed

client/app/devx/resources/page.tsx, client/app/globals.css, client/components/devx/resources/header.tsx, client/components/devx/resources/modal-landing.tsx, client/package-lock.json, client/tailwind.config.ts
Redesigned the resources page to improve navigation, usability, and visual appeal with an intuitive layout and enhanced interactivity.
Fixes #280
=> Fix: Redesign the resources page issue

client/components/playground/Header/index.tsx, client/components/playground/Playground.tsx
Closes #285 
https://github.com/user-attachments/assets/b4319b15-36af-4262-a765-c7517d23a34f
=> Feat: Fix devxstar UI

client/components/playground/floatingWindow/FloatingSidebar.tsx, client/tailwind.config.ts
Fixed the custom block creation modal to appear as a centered popup . Implemented proper animations, styling, and glowing effects while maintaining all existing functionality.
Key improvements:
- Fixed modal positioning to center of screen
- Added fade-in animation and backdrop blur
- Enhanced form styling and text visibility
- Added pulse animation to submit button
- Ensured created blocks match existing styling with glow effect
- Maintained all existing functionality
Closes #276
=> Feat/Fix the Custom Block Creation

client/app/api/generate-contract/route.ts, client/components/playground/Modal/Compile/GenerateCode.tsx, client/components/playground/Modal/Compile/index.tsx, client/lib/devxstark/dojo-contract-generator.ts, client/lib/devxstark/prompt-generate.ts
This PR introduces a new Dojo option when generating smart contract code in the DevXStark Playground that adds Dojo Contracts generation.
Fixes #284
=> Add Dojo Contract Generator

client/app/devx/contracts/applications/erc20-token/page.tsx, client/app/devx/contracts/applications/erc721-nft/page.tsx, client/app/devx/contracts/components/storage/page.tsx, client/app/devx/contracts/getting-started/build/page.tsx, client/app/devx/contracts/getting-started/create/page.tsx, client/components/devx/contracts/Accordion.tsx, client/components/devx/contracts/Sidebar.tsx
Fixed the sidebar ui and also displayed contracts on website
Fixes #278
=> examples-contract-page-#278

client/app/devx/contracts/applications/erc20-token/page.tsx, client/app/devx/contracts/applications/erc721-nft/page.tsx, client/app/devx/contracts/components/storage/page.tsx, client/app/devx/contracts/getting-started/build/page.tsx, client/app/devx/contracts/getting-started/create/page.tsx, client/components/devx/contracts/Accordion.tsx, client/components/devx/contracts/Sidebar.tsx
Reverts Shonen-Labs/StarkFinder#294
=> Revert "examples-contract-page-#278"

contracts/Quadratic.cairo
=> feat: added quadratic voting contract

contracts/RugPull/lib.cairo, contracts/RugPull/models.cairo, contracts/RugPull/systems/actions.cairo, contracts/RugPull/tests/tests.cairo
=> Added rugpull contract

.github/workflows/ci-cd.yml, contracts/.tool-versions, contracts/tests/lib.cairo, contracts/tests/test_basic.cairo, contracts/tests/test_constant_product_amm.cairo, contracts/tests/test_crowdfunding.cairo, contracts/tests/test_defi_contract.cairo, contracts/tests/test_erc20.cairo, contracts/tests/test_nft_dutch.cairo, contracts/tests/test_starkfinder.cairo, contracts/tests/test_starkidentity.cairo, contracts/tests/test_storage.cairo, contracts/tests/test_timelock.cairo, contracts/tests/test_upgradable_contract.cairo, package-lock.json
Fixed issues with contracts' tests not working.
Fixes #301
=> Fixed tests to find contracts

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Summary
This PR introduces major documentation updates to reflect the unified architecture, improved onboarding steps, and contributor workflow for StarkFinder. These changes aim to make the project more accessible to new developers and maintainers, while also formalizing the contribution process.
What's Included
README.md Overhaul
Describes StarkFinder’s unified vision and AI multi-agent architecture
Detailed setup instructions for both the client and tg_bot
Environment variable guide with optional and required fields
Docker and Kubernetes deployment guide
Synapse integration documentation
Expanded section on agents, features, and future plans
Contribution Workflow (CONTRIBUTING.md)
Added or updated contributor instructions
Branching strategy, local dev setup, and testing guidelines …
=> Documentation & Contributor Guide

contracts/src/identityregistry.cairo, contracts/src/interfaces.cairo, contracts/src/interfaces/IIdentityRegistry.cairo, contracts/src/lib.cairo, contracts/tests/lib.cairo, contracts/tests/test_identity_registry.cairo
This pull request introduces a comprehensive implementation of an **Identity Registry** contract for StarkNet. The changes include the core contract, interface definitions, integration with existing modules, and a suite of unit tests to ensure correct functionality. The Identity Registry enables credential issuance, revocation, and governance over whitelisted issuers, enhancing identity management capabilities on StarkNet.
Fixes #270
=> feat: add decentralized identity contract with revocable credentials

UPDATED README.md
Added DeepSeek support for StarkNet contract auditing via streaming API
=> Create UPDATED README.md

client/app/api/deploy-contract/route.ts, client/app/devx/profile/[id]/page.tsx
This PR implements the full flow for fetching and displaying deployed contracts associated with the authenticated user.
**Key Updates:**
* ✅ **Backend Integration**:
Added the `GET` handler in `api/deploy-contract` to retrieve all contracts deployed by the authenticated user using their `userId`.
* 🎯 **Frontend Integration**:
* Fetched deployed contracts on the client side.
* Rendered contract list with metadata including contract name, address, and creation date.
* 📋 **Copy Feature**:
* Added a copy-to-clipboard icon next to each contract address for quick copying.
* 🔗 **Explorer Integration**:
* Added a "View on Explorer" link next to contract addresses to navigate directly to the respective blockchain explorer page.
Fixes #379 
Please …
=> feat: fetch all deployed contracts for the authenticated user on profile

client/app/api/generate-contract/route.ts, client/components/playground/Modal/Compile/ContractCode.tsx, client/components/playground/Modal/Compile/GenerateCode.tsx, client/components/playground/Modal/Compile/index.tsx, contracts/Scarb.toml, contracts/src/lib.cairo
This PR fixes `contract generation` in `devx`
Fixes #360 
=> fix: contract generation in devx

client/components/playground/Blocknode/BurnNode.tsx, client/components/playground/Blocknode/MintNode.tsx, client/components/playground/Blocknode/TransferNode.tsx, client/components/playground/Blocknode/index.tsx, client/components/playground/FloatingSidebar/constants/blockReferences.ts, client/components/playground/FloatingSidebar/constants/menuItems.ts, client/components/playground/FloatingSidebar/data.ts, client/components/playground/FloatingSidebar/index.tsx
Fixed sidebar block naming inconsistencies and incorrect contract flow generation for token-related blocks. This PR addresses UI issues where "Mint Tokens", "Burn Tokens", and "Transfer Tokens" blocks were not displaying correctly, and corrects the trigger action labels for "Initialize" and "Disconnect" blocks.
**Key Changes:**
- Added the Resources page redirect below the Contracts
- Removed the entire green section
- Created dedicated components for token operations (MintNode.tsx, BurnNode.tsx, TransferNode.tsx)
- Updated block routing logic in Blocknode/index.tsx to properly render specialized components
- Corrected trigger action text labels in menuItems.ts and data.ts
- Updated block definitions and references for proper contract flow generation
Fixes #364 
Please delete options that …
=> Fix: Enhance the DevX sidebar

client/app/page.tsx
=> landing page

client/app/devx/profile/[id]/page.tsx
This PR improves the **User Profile Page UI** to align with the StarkFinder design system.  
- Added **Navbar** with branding and Connect Wallet button  
- Added **Sidebar** with navigation (Home, Generated, Deployed, Settings)  
- Updated profile header with glassmorphism styling and gradient avatar  
- Redesigned contract cards (glass style, explorer link, copy button, OpenEditorButton restored)  
- Preserved backend logic and API integrations (no server changes)  
- Added error `Retry` button and consistent loading state  
Fixes #442 
---
-  Bug fix (non-breaking change which fixes an issue)
-  Documentation update
---
-  My code follows the style guidelines of this project  
-  I have performed a self-review of my own code  
-  My changes generate no new warnings  
-  No breaking …
=> Add a Navbar,a Footer,a Sidebar

.github/workflows/python-backend.yml
This PR adds a **CI/CD workflow for the Python backend (`py-be/`)**.  
The workflow includes:  
- **Linting job** - runs `black` and `isort` checks.  
- **Testing job** - runs `pytest` if available (safe fallback message if not installed).  
pytest is not currently listed in pyproject.toml dev dependencies.
The test job is included but will not run successfully until pytest is added.
Please confirm if you’d like me to adjust this workflow to skip tests for now, or leave it in place ready for when pytest is added.
---
Fixes #497  
---
---
- Verified workflow syntax locally (`act` or `yaml` lint).  
- Ensured caching, Poetry setup, and lint steps match `pyproject.toml`.  
- Test job runs safely even without `pytest` installed (prints message instead of failing).  
---
N/A  
---
=> (feat: .github):CICD:: Create Python backend CICD pipelines

client/components/Header.tsx, client/lib/Connect.tsx, client/lib/StarknetProvider.tsx, package.json
Fixed critical wallet connection issues that were preventing users from connecting their wallets to the dApp.
Fixes #446 
[https://www.loom.com/share/41eb963e5f2e4e98bb10b66e0394cc20?sid=48ea7285-0742-47b4-a7d3-a79c5069342a](https://www.loom.com/share/41eb963e5f2e4e98bb10b66e0394cc20?sid=48ea7285-0742-47b4-a7d3-a79c5069342a)
=> fix: connect wallet error

anon/client/app/about/page.tsx
=> Added Navbar and Footer to the About Page

client/components/playground/FloatingSidebar/index.tsx
Removed the entire Dojo Section from the sidebar along with the toggle button between Starknet and Dojo
Fixes #443 
=> Fix: Devx sidebar fixed

client/app/api/reviews/preview/route.ts, client/app/api/reviews/submit/route.ts, client/app/api/reviews/tags/route.ts, client/app/api/reviews/timeframes/route.ts, client/app/review/page.tsx, client/components/Header.tsx, client/components/review/CharacterCounter.tsx, client/components/review/ReviewComposer.tsx, client/components/review/ReviewForm.tsx, client/components/review/SafetyIndicator.tsx, client/components/review/TagSelector.tsx, client/components/review/TimeframeWidget.tsx, client/components/review/index.ts, client/lib/review/api.ts, client/lib/review/types.ts, client/lib/review/utils.ts, client/lib/review/validation.ts, client/package-lock.json, client/package.json
This document provides a comprehensive summary of the Review Composer feature implementation for StarkFinder, addressing GitHub issue #464. The feature delivers a complete review writing experience with live safety hints, toxicity/PII warnings, character counting, tag selection, and seamless submission capabilities.
**Fixes #464**: Implement a Review Composer feature that allows users to write and submit reviews with real-time feedback, safety checks, and comprehensive form validation.
- ✅ **Review Composer Component** - Complete form with content, tags, and timeframe
- ✅ **Character Counter** - Real-time character count with visual progress indicators
- ✅ **Safety Indicators** - Live toxicity and PII detection warnings
- ✅ **Tag Selection System** - Multi-select with suggestions and …
=> Review composer

py-be/app/api/routes.py, py-be/app/models/base.py, py-be/tests/conftest.py, py-be/tests/test_deployed_contracts_complete.py, py-be/tests/test_deployed_contracts_integration.py, py-be/tests/test_deployed_contracts_simple.py
=> Test GET /deployed_contracts Endpoint

anon/backend/Cargo.lock, anon/backend/Cargo.toml, anon/backend/src/lib.rs, anon/backend/src/libs/db.rs, anon/backend/src/main.rs, anon/backend/src/routes/health.rs, anon/backend/tests/health_test.rs, anon/backend/tests/mod.rs, tatus
=> (Anon): Connect to Postgres (health check)

anon/client/app/review/page.tsx
=> reviewpage added

py-be/deduct.py
=> deduct nominal fees

anon/client/app/about/page.tsx
fixed navbar and footer links for proper workflow.
=> fix nav and footer links

anon/backend/Cargo.toml, anon/backend/src/libs/apispec.rs, anon/backend/src/main.rs, anon/backend/src/routes/health.rs, anon/backend/tests/health_test.rs
=> Add healthz endpoint and tests

client/app/api/deploy-contract/route.ts, client/lib/deploy/deployer.ts, client/lib/deploy/files.ts, client/lib/deploy/network.ts, client/lib/deploy/utils.ts, client/lib/deploy/validation.ts, client/package.json, client/pnpm-lock.yaml, client/types/deploy.ts
Refactor the deploy-contract, broke it down into components, other files, and link them together, maintaining it's functionality while making it easier for someone to work on. Did a seperation of concern.
Closes #422 
=> Restructure the deploy-contract API route
